title: Minimalistic
logo: /assets/img/logo.jpg
email: croot.dev@gmail.com
description: Minimalistic is a theme powered by Jekyll.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/croot-git
  - name: Homepage
    icon: <i class="fa-house"></i>
    link: https://www.roottech.co.kr

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
