title: CRoot blog
logo: /assets/img/logo.jpg
author: croot
email: croot.dev@gmail.com
description: CRoot blog
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: Homepage
    icon: <i class="fa-solid fa-link"></i>
    link: https://www.roottech.co.kr
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/croot-git

navigation:
  - name: 용어집
    link: /docs/glossary.html
  - name: 암기노트
    link: /docs/memorization-note.html
  - name: Readme
    link: /index.html
    sublist:
      - name: Image
        link: /index.html#small-image
